#!/bin/bash

mkdir -p "$HOME"/Pictures/Screenshots "$HOME"/Videos/Screencasts

ln -sf "$HOME"/dotfiles/.bashrc "$HOME"/.bashrc
ln -sf "$HOME"/dotfiles/.bash_profile "$HOME"/.bash_profile

ln -sf /home/juanes/dotfiles/omarchy/bindings.conf \
         /home/juanes/.config/hypr/bindings.conf

ln -sf /home/juanes/dotfiles/omarchy/default \
        /home/juanes/.config/uwsm/default

ln -sf /home/juanes/dotfiles/omarchy/looknfeel.conf \
         /home/juanes/.config/hypr/looknfeel.conf

ln -sf /home/juanes/dotfiles/omarchy/input.conf \
        /home/juanes/.config/hypr/input.conf

ln -sf "$HOME"/dotfiles/omarchy/00-keyboard.conf \
        "$HOME"/etc/X11/xorg.conf.d/00-keyboard.conf


hyprctl reload

echo "Dotfiles updated successfully!"

